# Generated by Django 4.1 on 2023-01-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
