# Generated by Django 4.1 on 2023-02-12 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Book Id')),
                ('image', models.ImageField(upload_to='', verbose_name='Book Image')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Is Issued')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Department Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Student Id')),
                ('image', models.ImageField(upload_to='', verbose_name='Avatar Image')),
                ('roll_number', models.CharField(max_length=20, verbose_name='Roll No')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact No')),
                ('batch', models.CharField(max_length=20, verbose_name='Batch')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iLibrary.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('issuee_id', models.CharField(max_length=50, verbose_name='Issuee Id')),
                ('issue_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Book Issue Id')),
                ('issue_date', models.DateTimeField(verbose_name='Date Added')),
                ('renew_date', models.DateTimeField(verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iLibrary.book', verbose_name='Book Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Issuer Id')),
            ],
            options={
                'verbose_name': 'IssueBook',
                'verbose_name_plural': 'IssueBooks',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee Id')),
                ('image', models.ImageField(upload_to='', verbose_name='Avatar Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact No')),
                ('designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iLibrary.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
